import Provider from '@/providers/Provider'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ToastContainer } from 'react-toastify'
import './globals.css'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'This is Layout Title',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="border border-black h-full">
      <body
        className={
          inter.className +
          `container mx-auto border flex items-center justify-center border-black h-full`
        }
      >
        <ToastContainer />
        <Provider>{children}</Provider>
      </body>
    </html>
  )
}
